image: Visual Studio 2019

environment:
  matrix:
  - solution_path: SimpleFTP\SimpleFTP.sln
  - solution_path: LazyThreads\LazyThreads.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test-script:
  - dotnet test --test-adapter-path:. --logger:Appveyor SimpleFTP\FTPServer.Tests\FTPServer.Tests.csproj
  - dotnet test --test-adapter-path:. --logger:Appveyor SimpleFTP\FTPClient.Tests\FTPClient.Tests.csproj