image: Visual Studio 2019

environment:
  matrix:
  - solution_path: Test1\Test1.sln
  - solution_path: SimpleFTP\SimpleFTP.sln
  - solution_path: TicTacToe\TicTacToe.sln
  - solution_path: MyNUnitWeb\MyNUnitWeb.sln
  - solution_path: LazyThreads\LazyThreads.sln
  - solution_path: SimpleThreadPool\SimpleThreadPool.sln
  - solution_path: MyNUnit\MyNUnit.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test --test-adapter-path:. --logger:Appveyor SimpleFTP\FTPServer.Tests\FTPServer.Tests.csproj
  - dotnet test --test-adapter-path:. --logger:Appveyor SimpleFTP\FTPClient.Tests\FTPClient.Tests.csproj