image: Visual Studio 2017

environment:
  matrix:
  - solution_path: MyNUnitWeb\MyNUnitWeb.sln
  - solution_path: LazyThreads\LazyThreads.sln
  - solution_path: SimpleThreadPool\SimpleThreadPool.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%