image: Visual Studio 2019

environment:
  matrix:
  - solution_path: SimpleFTP\SimpleFTP.sln
  - solution_path: LazyThreads\LazyThreads.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%